name: secs-tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.23'
    - name: run-tests
      uses: HorstBaerbel/action-ctest@1.1
      with:
        sourcedir: '.'
        builddir: 'build'
        cmakeoptions: '--config Release -DBUILD_TESTING=ON'
        ctestoptions: '-C Release' 
